const fs = require('fs');
const h = fs.readFileSync('index.html', 'utf8');
console.log('size:', h.length, 'bytes');
console.log('has slider:', h.includes('slider-wrap'));
console.log('has mini-card:', h.includes('mini-card'));
console.log('has nav-cats:', h.includes('nav-cats'));
console.log('has split:', h.includes('split-layout'));
const bodyEnd = h.indexOf('</body>');
console.log('body end at:', bodyEnd);
const jsStart = h.lastIndexOf('<script>', bodyEnd);
console.log('main JS at:', jsStart);
