/**
 * AI 硬件产品数据（80+款）
 * 按新分类整理
 */
module.exports = [
  // ===== 🏠 智能家居 (7) =====
  { id: 'mi-home', name: '米家', nameCn: '米家全屋智能', category: '智能家居', description: '小米旗下智能家居生态，覆盖照明、安防、家电等200+品类，AI联动场景控制', website: 'https://mi.com', specs: { 生态: '米家生态', 协议: 'Wi-Fi/蓝牙/Zigbee/蓝牙Mesh', 设备: '2000+款' }, pricing: '单品99元起', features: ['AI场景联动', '语音控制', '跨品牌联动', '自动化规则'], pros: ['品类最全', '性价比高', '生态丰富'], cons: ['部分需网关', '依赖小米生态'], bannerImage: '' },
  { id: 'aqara-hub', name: 'Aqara绿米', nameCn: 'Aqara全屋智能', category: '智能家居', description: '高端全屋智能品牌，HomeKit/米家双生态，Zigbee3.0稳定连接', website: 'https://aqara.com', specs: { 协议: 'Zigbee 3.0/Wi-Fi/蓝牙Mesh', 兼容: 'HomeKit/米家/Alexa', 设备: '500+款' }, pricing: '套装999元起', features: ['HomeKit原生支持', '多协议网关', '高端传感器', '安防联动'], pros: ['稳定性强', '多平台兼容', '品质感高'], cons: ['价格偏高', '需专业安装'], bannerImage: '' },
  { id: 'huawei-hilink', name: '华为全屋智能', nameCn: '华为全屋智能', category: '智能家居', description: '华为全屋智能解决方案，PLC+Wi-Fi双网络，HarmonyOS分布式控制', website: 'https://consumer.huawei.com', specs: { 网络: 'PLC+Wi-Fi 6+', 系统: 'HarmonyOS', 设备: '300+款' }, pricing: '全屋方案3万元起', features: ['PLC稳定连接', '鸿蒙分布式', '智能主机', '全屋场景联动'], pros: ['网络稳定', '华为生态', '企业级品质'], cons: ['价格高', '需华为手机配合'], bannerImage: '' },
  { id: 'haier-smart-fridge', name: '海尔AI冰箱', nameCn: '海尔AI智能冰箱', category: '智能家居', description: '海尔AI冰箱，食材智能识别管理，推荐健康食谱，语音交互', website: 'https://haier.com', specs: { AI功能: '食材识别/食谱推荐/语音控制', 屏幕: '21.5寸触控屏', 容量: '500L+' }, pricing: '5999元起', features: ['食材识别管理', '健康食谱推荐', '语音交互', '远程监控'], pros: ['AI食材管理', '大屏交互', '保鲜技术强'], cons: ['价格高', '大屏实用性争议'], bannerImage: '' },
  { id: 'huawei-smart-lock', name: '华为智能门锁', nameCn: '华为智能门锁', category: '智能家居', description: '华为AI3D人脸识别门锁，HarmonyOS分布式开锁，猫眼可视对讲', website: 'https://consumer.huawei.com', specs: { 解锁: '3D人脸/指纹/密码/NFC/钥匙', 电池: '8800mAh', 摄像: '1080P猫眼' }, pricing: '2499元起', features: ['3D人脸识别', 'AI猫眼监控', 'HarmonyOS一碰开', '异常告警'], pros: ['识别速度快', '生态联动', '安全等级高'], cons: ['价格高', '需定期充电'], bannerImage: '' },
  { id: 'mi-curtain', name: '米家智能窗帘', nameCn: '米家智能窗帘', category: '智能家居', description: '小米智能窗帘电机，语音控制开合，定时自动开合，光线感应联动', website: 'https://mi.com', specs: { 电机: '静音电机', 控制: '语音/APP/遥控', 噪音: '<35dB' }, pricing: '499元起', features: ['语音控制', '定时开合', '光线联动', '手拉启动'], pros: ['性价比高', '静音运行', '安装简单'], cons: ['需网关配合', '轨道路径受限'], bannerImage: '' },
  { id: 'broadlink-rm4', name: '博联RM4', nameCn: '博联智能遥控', category: '智能家居', description: '万能红外遥控器，AI学习红外码，APP远程控制传统家电', website: 'https://broadlink.com.cn', specs: { 支持: '红外/RF433', 码库: '50万+家电', 网络: '2.4GHz Wi-Fi' }, pricing: '149元', features: ['AI学习红外码', '50万+码库', '远程控制', '场景联动'], pros: ['万能遥控', '价格低', '码库丰富'], cons: ['仅红外/RF', '无蓝牙'], bannerImage: '' },

  // ===== 🤖 人形机器人 (8) =====
  { id: 'unitree-h1', name: 'Unitree H1', nameCn: '宇树人形机器人H1', category: '人形机器人', description: '宇树科技全尺寸人形机器人，3D激光雷达+深度相机，奔跑步速3.3m/s', website: 'https://unitree.com', specs: { 身高: '1.8m', 体重: '47kg', 自由度: '51', 奔跑步速: '3.3m/s' }, pricing: '65万元', features: ['全尺寸双足行走', '3.3m/s奔跑', '360°激光雷达', '力控关节'], pros: ['运动性能强', '性价比高', '开源生态'], cons: ['续航有限', '手部精细操作弱'], bannerImage: '' },
  { id: 'unitree-g1', name: 'Unitree G1', nameCn: '宇树人形机器人G1', category: '人形机器人', description: '宇树小型人形机器人，超迷你体积+高灵活性，AI学习人形动作', website: 'https://unitree.com', specs: { 身高: '1.27m', 体重: '35kg', 自由度: '23+', 负载: '2kg' }, pricing: '9.9万元', features: ['AI模仿学习', '柔性关节', '力控行走', '小体积灵活'], pros: ['价格突破', 'AI学习能力', '开源SDK'], cons: ['体型小限制场景', '手部操作有限'], bannerImage: '' },
  { id: 'ubtech-walker', name: 'Walker S', nameCn: '优必选Walker S人形机器人', category: '人形机器人', description: '优必选商用服务人形机器人，41个自由度，已入驻蔚来等汽车工厂', website: 'https://ubtech.com.cn', specs: { 身高: '1.7m', 体重: '77kg', 自由度: '41', 续航: '2h' }, pricing: '商用定制', features: ['41自由度', '汽车工厂应用', '柔性力控', '多模态交互'], pros: ['商用成熟', '工业级可靠性', '交互自然'], cons: ['价格高', '重量大'], bannerImage: '' },
  { id: 'agibot-a2', name: '智元A2', nameCn: '智元远征A2人形机器人', category: '人形机器人', description: '智元机器人旗舰人形产品，开源具身智能框架，支持G1到G5任务难度', website: 'https://agibot.com', specs: { 身高: '1.75m', 体重: '55kg', 自由度: '49', 负载: '5kg' }, pricing: '商用定制', features: ['开源具身智能', '灵巧手操作', '多模态感知', '5kg负载'], pros: ['开源生态', '灵巧手强', '开发者友好'], cons: ['新品牌', '商用案例少'], bannerImage: '' },
  { id: 'xiaopeng-iron', name: '小鹏Iron', nameCn: '小鹏Iron人形机器人', category: '人形机器人', description: '小鹏鹏行L3级人形机器人，62个主动自由度，AI鹰眼视觉，2026年量产', website: 'https://xiaopeng.com', specs: { 身高: '1.78m', 自由度: '62', 视觉: 'AI鹰眼系统', 量产: '2026年' }, pricing: '待定', features: ['62自由度', 'AI鹰眼视觉', '触觉仿真手', '工厂产线应用'], pros: ['自由度最高', '车企量产', '触觉反馈'], cons: ['未量产', '价格未知'], bannerImage: '' },
  { id: 'stardust-s1', name: 'Astribot S1', nameCn: '星尘智能S1机器人', category: '人形机器人', description: '星尘智能AI机器人助理，弹琴喂猫煎饼泡茶，长序列泛化任务执行', website: 'https://astribot.com', specs: { 速度: '3m/s', 臂: '双7DOF臂', 手: '灵巧手', 任务: '弹琴/烹饪/家务' }, pricing: '商用定制', features: ['长序列任务', '双臂协调', '精细操作', '人形交互'], pros: ['操作精细', '任务泛化强', '交互自然'], cons: ['初创公司', '产量有限'], bannerImage: '' },
  { id: 'fourier-gr1', name: '傅利叶GR-1', nameCn: '傅利叶GR-1人形机器人', category: '人形机器人', description: '傅利叶智能通用人形机器人，已实现量产交付，医疗康复+工业场景', website: 'https://fourierintelligence.com', specs: { 身高: '1.65m', 体重: '55kg', 自由度: '40', 速度: '1.5m/s' }, pricing: '商用定制', features: ['量产交付', '医疗康复应用', '力控关节', '模块化设计'], pros: ['已量产', '医疗背景', '稳定性高'], cons: ['运动速度一般', '场景偏窄'], bannerImage: '' },
  { id: 'unitree-go2', name: 'Unitree Go2', nameCn: '宇树四足机器人Go2', category: '人形机器人', description: '宇树科技四足机器人，AI大模型加持，超感知系统，工业巡检+消费陪伴', website: 'https://unitree.com', specs: { 体重: '15kg', 负载: '3-5kg', 速度: '2.5m/s', 续航: '2-4h' }, pricing: '9997元起', features: ['AI大模型交互', '超感知系统', '4D激光雷达', '足式运动'], pros: ['价格亲民', '运动能力强', 'SDK开放'], cons: ['四足非人形', '消费级场景少'], bannerImage: '' },

  // ===== 🧹 扫地机器人 (5) =====
  { id: 'ecovacs-x9', name: '科沃斯X9', nameCn: '科沃斯地宝X9', category: '扫地机器人', description: '科沃斯旗舰扫地机器人，OZMO Turbo2.0双滚刷，AIVI 3D避障', website: 'https://ecovacs.com', specs: { 吸力: '8800Pa', 导航: 'dToF+AIVI 3D', 拖地: '双旋转拖布', 电池: '6400mAh' }, pricing: '5999元', features: ['AIVI 3D避障', '双滚刷系统', '自动集尘换水', '语音控制'], pros: ['避障精准', '清洁力强', '全能基站'], cons: ['价格高', '噪音较大'], bannerImage: '' },
  { id: 'roborock-saros-z70', name: 'Roborock Saros Z70', nameCn: '石头Saros Z70', category: '扫地机器人', description: '石头科技旗舰扫地机，搭载仿生机械手，可抓取移动物品，CES2025明星产品', website: 'https://roborock.com', specs: { 机械臂: '仿生机械手', 吸力: '11000Pa', 导航: '结构光+AI', 拖地: '声波震动' }, pricing: '6999元', features: ['仿生机械手抓取', 'AI物体识别', '自动上下水', '视频通话'], pros: ['革命性机械手', '吸力顶级', '自动化高'], cons: ['价格最高', '机械臂精度有限'], bannerImage: '' },
  { id: 'narwal-s9', name: 'Narwal S9', nameCn: '云鲸S9扫拖机器人', category: '扫地机器人', description: '云鲸旗舰扫拖机器人，气旋集尘+自动洗拖布，智能脏污感应', website: 'https://narwal.com', specs: { 吸力: '10000Pa', 拖地: '三角拖布旋转', 基站: '气旋集尘+热水洗', 电池: '5200mAh' }, pricing: '4999元', features: ['脏污感应', '热水洗拖布', '气旋集尘', '自动添加清洁液'], pros: ['拖地效果好', '基站自动化', '噪音低'], cons: ['避障一般', 'App体验待提升'], bannerImage: '' },
  { id: 'dreame-x50', name: 'Dreame X50', nameCn: '追觅X50扫拖机器人', category: '扫地机器人', description: '追觅旗舰扫拖机器人，仿生双机械足越障，AI视觉避障', website: 'https://dreame.com', specs: { 吸力: '13000Pa', 机械足: '仿生双机械足', 导航: 'AI视觉+3D结构光', 拖地: '主动式双旋转' }, pricing: '5999元', features: ['仿生足越障', '13000Pa吸力', 'AI避障', '全能基站'], pros: ['越障能力强', '吸力最强', '创新设计'], cons: ['品牌年轻', '新品稳定性待验'], bannerImage: '' },
  { id: 'ecovacs-t30', name: '科沃斯T30', nameCn: '科沃斯地宝T30', category: '扫地机器人', description: '科沃斯性价比旗舰，ZeroTangle防缠绕毛刷，TruEdge沿边清洁', website: 'https://ecovacs.com', specs: { 吸力: '7300Pa', 毛刷: 'ZeroTangle防缠绕', 沿边: 'TruEdge沿边', 电池: '5200mAh' }, pricing: '3999元', features: ['防缠绕毛刷', '沿边清洁', '自动集尘', 'YIKO语音'], pros: ['性价比高', '防缠绕', '沿边到位'], cons: ['避障降级', '拖布不可抬升'], bannerImage: '' },

  // ===== 👓 AI眼镜 (8) =====
  { id: 'raybird-v3', name: '雷鸟V3', nameCn: '雷鸟V3 AI眼镜', category: 'AI眼镜', description: '雷鸟创新旗舰AI拍摄眼镜，搭载阿里通义大模型，1600万像素摄像头，15小时续航', website: 'https://raybird.com', specs: { 摄像头: '1600万像素', AI模型: '通义大模型', 续航: '15小时', 重量: '39g' }, pricing: '1799元', features: ['通义大模型对话', '1600万像素拍摄', '15h超长续航', '语音翻译'], pros: ['续航最长', 'AI大模型集成', '拍摄清晰'], cons: ['无AR显示', '品牌认知度一般'], bannerImage: '' },
  { id: 'raybird-x3', name: '雷鸟X3', nameCn: '雷鸟X3 AR眼镜', category: 'AI眼镜', description: '雷鸟创新AR显示眼镜，MicroLED+光波导，CES2026亮相', website: 'https://raybird.com', specs: { 显示: 'MicroLED光波导', 视场角: '35°', 亮度: '1500nit', AI: '通义大模型' }, pricing: '待定', features: ['MicroLED显示', '光波导方案', 'AI助手', '轻量化'], pros: ['显示技术领先', '融资10亿', '运营商背书'], cons: ['未上市', '价格未知'], bannerImage: '' },
  { id: 'shanjii-shooting', name: '闪极拍拍镜', nameCn: '闪极AI拍拍镜', category: 'AI眼镜', description: '闪极科技AI拍摄眼镜，1600万像素，第一视角直播录制，AI识物翻译', website: 'https://shanjii.com', specs: { 摄像头: '1600万像素', 视频: '1080P录制', 续航: '12小时', 重量: '45g' }, pricing: '999元', features: ['第一视角录制', 'AI识物翻译', '直播推流', '轻量佩戴'], pros: ['价格最低', '拍摄方便', '直播功能'], cons: ['无AR显示', '品牌新'], bannerImage: '' },
  { id: 'rokid-ar-lite', name: 'Rokid AR Lite', nameCn: 'Rokid AR Lite眼镜', category: 'AI眼镜', description: '若琪AR智能眼镜，空间显示+AI语音助手，B端C端双布局', website: 'https://rokid.com', specs: { 显示: 'Birdbath光学', 视场角: '40°', 分辨率: '1080P', 重量: '75g' }, pricing: '3499元', features: ['空间显示', 'AI语音助手', '手势交互', '多场景适配'], pros: ['显示效果好', '生态成熟', '手势交互'], cons: ['价格偏高', '重量偏重'], bannerImage: '' },
  { id: 'qwen-glasses', name: '千问AI眼镜', nameCn: '千问AI眼镜', category: 'AI眼镜', description: '阿里巴巴旗下千问品牌首款AI眼镜，MWC2026发布，通义大模型深度集成', website: 'https://qwen.ai', specs: { AI模型: '通义千问', 发布: 'MWC 2026', 功能: 'AI对话/翻译/识物' }, pricing: '待定', features: ['通义千问深度集成', '阿里生态联动', 'AI识物翻译', '语音交互'], pros: ['阿里生态', '大模型能力强', '品牌信任'], cons: ['未上市', '规格未公布'], bannerImage: '' },
  { id: 'inmo-air3', name: 'INMO Air3', nameCn: 'INMO Air3智能眼镜', category: 'AI眼镜', description: 'INMO影目科技AR眼镜，全彩MicroLED显示，独立WiFi联网', website: 'https://inmo.com', specs: { 显示: '全彩MicroLED', 系统: 'INMO OS', 网络: '独立WiFi', 摄像头: '1200万像素' }, pricing: '2999元', features: ['全彩AR显示', '独立联网', 'AI助手', '语音翻译'], pros: ['独立运行', '显示效果好', '翻译实用'], cons: ['续航一般', '应用生态少'], bannerImage: '' },
  { id: 'halliday-glasses', name: 'Halliday', nameCn: 'Halliday AI眼镜', category: 'AI眼镜', description: 'Halliday AI眼镜，DigiWindow视网膜投影技术，众筹爆款', website: 'https://halliday.com', specs: { 显示: 'DigiWindow视网膜投影', 重量: '35g', 功能: 'AI翻译/提词/导航', 续航: '8小时' }, pricing: '1999元', features: ['视网膜投影', '隐形显示', 'AI翻译提词', '超轻35g'], pros: ['显示技术独特', '重量最轻', '提词实用'], cons: ['显示面积小', '续航一般'], bannerImage: '' },
  { id: 'baidu-ruizi', name: '百度小度AI眼镜', nameCn: '小度AI眼镜', category: 'AI眼镜', description: '百度旗下小度AI眼镜，文心大模型加持，第一视角AI助手', website: 'https://xiaodu.com', specs: { AI模型: '文心大模型', 摄像头: '1600万像素', 续航: '10小时', 重量: '42g' }, pricing: '待定', features: ['文心大模型', 'AI识物问答', '实时翻译', '第一视角记录'], pros: ['百度AI能力', '小度生态', '搜索能力'], cons: ['未正式发售', '品牌定位模糊'], bannerImage: '' },

  // ===== 🔊 智能音箱 (3) =====
  { id: 'xiaodu-speaker', name: '小度智能音箱', nameCn: '小度智能音箱', category: '智能音箱', description: '百度旗下智能音箱，文心大模型加持，连续对话+多轮交互+全屋控制', website: 'https://xiaodu.com', specs: { AI: '文心大模型', 麦克风: '6麦克风阵列', 智能家居: '500+品牌' }, pricing: '299元起', features: ['文心大模型对话', '连续对话', '全屋控制', '儿童模式'], pros: ['AI能力强', '生态丰富', '价格亲民'], cons: ['音质一般', '广告推送'], bannerImage: '' },
  { id: 'tmall-genie', name: '天猫精灵', nameCn: '天猫精灵', category: '智能音箱', description: '阿里巴巴旗下智能音箱，通义大模型加持，淘宝购物+全屋智能', website: 'https://tmall.com', specs: { AI: '通义大模型', 内容: '酷狗/喜马拉雅', 智能家居: '300+品牌' }, pricing: '199元起', features: ['通义大模型', '淘宝语音购物', '全屋控制', '视频通话'], pros: ['购物体验好', '内容丰富', '价格低'], cons: ['音质一般', '阿里生态绑定'], bannerImage: '' },
  { id: 'xiaoai-speaker', name: '小爱同学', nameCn: '小爱同学智能音箱', category: '智能音箱', description: '小米旗下智能音箱，米家生态核心入口，6亿+设备连接', website: 'https://mi.com', specs: { AI: '小爱同学', 设备连接: '6亿+', 智能家居: '米家全生态' }, pricing: '249元起', features: ['米家生态核心', '6亿设备连接', '连续对话', '多房间控制'], pros: ['米家生态最全', '设备支持多', '性价比高'], cons: ['音质一般', '偶尔误唤醒'], bannerImage: '' },

  // ===== 📚 AI学习机 (5) =====
  { id: 'iflytek-learning', name: '科大讯飞AI学习机', nameCn: '科大讯飞AI学习机', category: 'AI学习机', description: '科大讯飞旗舰AI学习机，星火大模型驱动，精准学诊断+AI一对一个性化辅导', website: 'https://iflytek.com', specs: { AI: '讯飞星火大模型', 屏幕: '13.3寸2K', 存储: '8+256GB', 电池: '10000mAh' }, pricing: '6999元起', features: ['星火大模型辅导', '精准学诊断', 'AI作文批改', '家长管控'], pros: ['AI教学最强', '诊断精准', '内容权威'], cons: ['价格最高', '应用商店受限'], bannerImage: '' },
  { id: 'xueersi-learning', name: '学而思学习机', nameCn: '学而思AI学习机', category: 'AI学习机', description: '好未来旗下学习机，自研内容+AI老师，数学思维培养特色', website: 'https://xueersi.com', specs: { AI: '自研AI老师', 屏幕: '12.35寸', 存储: '8+256GB', 内容: '学而思自研' }, pricing: '5999元起', features: ['自研教学内容', 'AI老师互动', '数学思维特色', '分层教学'], pros: ['内容质量高', '数学特色强', '体系完整'], cons: ['理科偏强文科弱', '价格偏高'], bannerImage: '' },
  { id: 'bbk-learning', name: '步步高学习机', nameCn: '步步高AI学习机', category: 'AI学习机', description: '步步高教育电子出品，AI精准学+护眼屏，覆盖小学到高中', website: 'https://bbk.com', specs: { AI: 'AI精准学', 屏幕: '12.7寸护眼', 存储: '6+128GB', 覆盖: '小初高全科目' }, pricing: '4999元起', features: ['AI精准学', '护眼认证', '全科目覆盖', '家长远程管控'], pros: ['品牌信任度高', '护眼认证', '全科目'], cons: ['AI能力不如讯飞', '内容更新慢'], bannerImage: '' },
  { id: 'youxuepai-learning', name: '优学派学习机', nameCn: '优学派AI学习机', category: 'AI学习机', description: '优学派AI学习机，AI知识图谱诊断，个性化学习路径', website: 'https://youxuepai.com', specs: { AI: 'AI知识图谱', 屏幕: '11寸', 存储: '6+128GB', 特色: '知识图谱诊断' }, pricing: '3999元起', features: ['知识图谱诊断', '个性化路径', 'AI错题本', '名师课堂'], pros: ['价格亲民', '诊断有特色', '错题管理'], cons: ['品牌影响力弱', '内容深度一般'], bannerImage: '' },
  { id: 'dji-tutor', name: '大疆萤火虫Tutor', nameCn: '大疆萤火虫AI教学机器人', category: 'AI学习机', description: '大疆教育出品AI教学机器人，编程+机器人+AI三合一，STEAM教育', website: 'https://dji.com', specs: { 类型: '编程教学机器人', 编程: 'Scratch/Python', AI: '视觉识别/语音', 适用: '8岁+' }, pricing: '2999元', features: ['Scratch+Python编程', 'AI视觉识别', '机器人搭建', 'STEAM课程'], pros: ['动手实践', '编程启蒙', '大疆品质'], cons: ['学科辅导弱', '年龄限制'], bannerImage: '' },

  // ===== 🛩️ 无人机 (4) =====
  { id: 'dji-mini4', name: 'DJI Mini 4', nameCn: '大疆Mini 4无人机', category: '无人机', description: '大疆最轻便航拍无人机，249g无需注册，4K/60fps HDR视频', website: 'https://dji.com', specs: { 重量: '249g', 视频: '4K/60fps HDR', 续航: '34min', 图传: 'O4 20km' }, pricing: '4788元起', features: ['4K HDR视频', '249g免注册', 'O4图传', '智能跟随5.0'], pros: ['最轻便', '画质优秀', '无需注册'], cons: ['抗风一般', '无避障侧向'], bannerImage: '' },
  { id: 'dji-avata2', name: 'DJI Avata 2', nameCn: '大疆Avata 2飞行眼镜', category: '无人机', description: '大疆沉浸式飞行体验无人机，体感操控+飞行眼镜，4K超广角', website: 'https://dji.com', specs: { 重量: '377g', 视频: '4K/60fps', 视角: '155°超广角', 图传: 'O4' }, pricing: '6988元起', features: ['体感操控', '飞行眼镜沉浸', '155°超广角', '一键花飞'], pros: ['沉浸体验', '操控直觉', '安全易飞'], cons: ['续航偏短', '需配眼镜'], bannerImage: '' },
  { id: 'dji-mavic3', name: 'DJI Mavic 3', nameCn: '大疆Mavic 3专业无人机', category: '无人机', description: '大疆旗舰航拍无人机，哈苏相机+全向避障，专业影视级画质', website: 'https://dji.com', specs: { 相机: '哈苏4/3 CMOS', 视频: '5.1K/50fps', 续航: '43min', 避障: '全向感知' }, pricing: '13888元起', features: ['哈苏相机', '5.1K视频', '全向避障', '43分钟续航'], pros: ['画质顶级', '避障全面', '专业可靠'], cons: ['价格高', '体积偏大'], bannerImage: '' },
  { id: 'dji-robomaster', name: 'DJI RoboMaster', nameCn: '大疆RoboMaster教育机器人', category: '无人机', description: '大疆教育机器人平台，AI视觉+编程操控，全国大学生机器人大赛官方平台', website: 'https://dji.com', specs: { 类型: '教育机器人', 编程: 'Python/C++', AI: '视觉识别/自动瞄准', 赛事: 'RoboMaster大赛' }, pricing: '4999元起', features: ['AI视觉识别', '编程操控', '竞赛平台', '模块化设计'], pros: ['赛事生态', '编程深度', '教学体系'], cons: ['学习曲线陡', '配件贵'], bannerImage: '' },

  // ===== 🗣️ 翻译录音 (4) =====
  { id: 'iflytek-translator', name: '讯飞翻译机', nameCn: '科大讯飞翻译机', category: '翻译录音', description: '科大讯飞AI翻译机，支持83种语言在线翻译，方言识别，离线翻译', website: 'https://iflytek.com', specs: { 语言: '83种在线', 离线: '中英日韩', 方言: '粤语/四川话等', 拍照: 'OCR翻译' }, pricing: '2999元', features: ['83种语言翻译', '方言识别', '离线翻译', '拍照翻译'], pros: ['翻译准确率高', '方言支持', '离线可用'], cons: ['价格偏高', '需联网功能多'], bannerImage: '' },
  { id: 'iflytek-recorder', name: '讯飞录音笔', nameCn: '科大讯飞智能录音笔', category: '翻译录音', description: '科大讯飞AI录音笔，实时语音转文字，多语言识别，会议纪要自动生成', website: 'https://iflytek.com', specs: { 转写: '实时语音转文字', 语言: '中文/英/日/韩', 存储: '32GB', 续航: '10h录音' }, pricing: '1999元起', features: ['实时转文字', '多语言识别', '会议纪要生成', 'OCR摘录'], pros: ['转写准确', '效率提升大', '专业场景强'], cons: ['价格偏高', '嘈杂环境降准'], bannerImage: '' },
  { id: 'sogou-recorder', name: '搜狗录音笔', nameCn: '搜狗AI录音笔', category: '翻译录音', description: '搜狗AI录音笔，同声传译+录音转写，支持多语言实时翻译', website: 'https://sogou.com', specs: { 转写: '录音转文字', 翻译: '中英同传', 存储: '16GB', 续航: '8h' }, pricing: '999元起', features: ['同声传译', '录音转写', '多语言翻译', '云端同步'], pros: ['价格低', '同传实用', '小巧便携'], cons: ['准确率不如讯飞', '品牌存续不确定'], bannerImage: '' },
  { id: 'timekettle-m2', name: 'Timekettle M2', nameCn: '时空壶M2翻译耳机', category: '翻译录音', description: '时空壶同声翻译耳机，双人同戴实时翻译，40种语言', website: 'https://timekettle.co', specs: { 语言: '40种', 模式: '触控/同声/旁听', 耳机: 'TWS降噪', 续航: '5h' }, pricing: '1299元', features: ['同声翻译耳机', '40种语言', '触控模式', '降噪通话'], pros: ['佩戴翻译', '实时性好', '多场景'], cons: ['翻译延迟', '嘈杂环境差'], bannerImage: '' },

  // ===== 📷 智能摄像 (4) =====
  { id: 'ezviz-camera', name: '萤石智能摄像机', nameCn: '萤石AI智能摄像机', category: '智能摄像', description: '海康威视旗下萤石品牌，AI人形检测+哭声检测+追踪，家庭安防首选', website: 'https://ezviz.com', specs: { 分辨率: '2K/3K', AI: '人形/车辆/哭声检测', 存储: '云存+本地', 夜视: '全彩夜视' }, pricing: '199元起', features: ['AI人形检测', '哭声检测', '追踪跟拍', '全彩夜视'], pros: ['安防专业', '价格低', '海康背书'], cons: ['云存需付费', 'App广告多'], bannerImage: '' },
  { id: 'xiaovv-camera', name: '小维智能摄像机', nameCn: '小维AI智能摄像机', category: '智能摄像', description: '小维AI摄像头，人形侦测+智能追踪，手机远程查看，性价比高', website: 'https://xiaovv.com', specs: { 分辨率: '1080P/2K', AI: '人形侦测/追踪', 存储: '云存+TF卡', 夜视: '红外夜视' }, pricing: '129元起', features: ['人形侦测', '智能追踪', '手机远程', '双向语音'], pros: ['价格极低', '安装简单', '基础功能全'], cons: ['画质一般', '云存需付费'], bannerImage: '' },
  { id: 'huawei-smart-cam', name: '华为智选摄像机', nameCn: '华为智选AI摄像机', category: '智能摄像', description: '华为智选智能摄像机，HarmonyOS一碰联网，AI人形检测+哭声检测', website: 'https://consumer.huawei.com', specs: { 分辨率: '2K', AI: '人形/哭声检测', 联网: 'HarmonyOS一碰连', 存储: '云存+本地' }, pricing: '249元起', features: ['鸿蒙一碰连', 'AI人形检测', '哭声检测', '隐私遮蔽'], pros: ['鸿蒙生态', '连接方便', '隐私保护'], cons: ['款式少', '价格偏高'], bannerImage: '' },
  { id: 'mi-camera', name: '米家智能摄像机', nameCn: '米家AI智能摄像机', category: '智能摄像', description: '小米米家智能摄像机，AI看家+哭声检测，米家生态联动', website: 'https://mi.com', specs: { 分辨率: '2K/3K', AI: '人形/哭声检测', 联动: '米家全生态', 存储: '云存+TF卡' }, pricing: '179元起', features: ['AI看家', '哭声检测', '米家联动', '双云台'], pros: ['米家生态', '价格低', '联动丰富'], cons: ['云存需付费', '偶有延迟'], bannerImage: '' },

  // ===== 🍽️ 服务机器人 (5) =====
  { id: 'pudu-bot', name: '普渡送餐机器人', nameCn: '普渡送餐机器人', category: '服务机器人', description: '普渡科技送餐机器人，餐饮行业市占率第一，3层托盘+自动回充', website: 'https://pudurobotics.com', specs: { 托盘: '3层', 负载: '30kg', 续航: '8-10h', 导航: '激光+视觉' }, pricing: '商用定制', features: ['3层托盘送餐', '自动回充', '多楼层运行', '语音交互'], pros: ['市占率第一', '稳定可靠', '餐厅首选'], cons: ['仅室内', '需改装通道'], bannerImage: '' },
  { id: 'keenon-robot', name: '擎朗送餐机器人', nameCn: '擎朗送餐机器人', category: '服务机器人', description: '擎朗智能送餐机器人，花生/飞鱼系列，全球60+国家部署', website: 'https://keenon.com', specs: { 托盘: '3-4层', 负载: '30kg+', 续航: '10h+', 覆盖: '60+国家' }, pricing: '商用定制', features: ['多楼层配送', '60国部署', '语音交互', '自动避障'], pros: ['全球化', '稳定性高', '款式多'], cons: ['价格高', '需专业部署'], bannerImage: '' },
  { id: 'orion-star-bot', name: '猎户星空服务机器人', nameCn: '猎户星空服务机器人', category: '服务机器人', description: '猎豹移动旗下，接待/配送/新零售多场景，AI语音交互', website: 'https://orionstar.com', specs: { 场景: '接待/配送/零售', AI: '语音交互+导航', 屏幕: '27寸触控', 续航: '8h' }, pricing: '商用定制', features: ['多场景服务', 'AI语音交互', '触屏点单', '自主导航'], pros: ['场景丰富', '交互自然', '猎豹AI能力'], cons: ['品牌影响力下降', '部署复杂'], bannerImage: '' },
  { id: 'yunji-robot', name: '云迹服务机器人', nameCn: '云迹酒店服务机器人', category: '服务机器人', description: '云迹科技酒店服务机器人，客房配送+引领带路，万豪等五星酒店标配', website: 'https://yunji.ai', specs: { 场景: '酒店客房配送', 乘梯: '自动乘梯', 负载: '10kg', 续航: '12h' }, pricing: '商用定制', features: ['客房配送', '自动乘梯', '引领带路', '电话联动'], pros: ['酒店市占率高', '五星酒店标配', '乘梯方案成熟'], cons: ['仅酒店场景', '成本高'], bannerImage: '' },
  { id: 'panghai-robot', name: '泛海科技消毒机器人', nameCn: '泛海AI消毒机器人', category: '服务机器人', description: '泛海科技紫外线+过氧化氢消毒机器人，医院/学校/商场防疫消毒', website: 'https://panghai.com', specs: { 方式: '紫外线+雾化消毒', 覆盖: '99.99%杀菌', 续航: '4-6h', 导航: '激光SLAM' }, pricing: '商用定制', features: ['双模式消毒', '自主导航', '远程控制', '消毒记录'], pros: ['杀菌彻底', '无人值守', '多场景适用'], cons: ['单价高', '维护成本高'], bannerImage: '' },

  // ===== 🏭 工业机器人 (6) =====
  { id: 'jaka-robot', name: 'JAKA节卡', nameCn: '节卡协作机器人', category: '工业机器人', description: '节卡机器人国内协作机器人龙头，6轴协作臂，拖动示教+图形化编程', website: 'https://jaka.com', specs: { 负载: '3-20kg', 臂展: '600-1353mm', 精度: '±0.02mm', 编程: '拖动示教' }, pricing: '5万元起', features: ['拖动示教', '图形化编程', '高精度', '安全协作'], pros: ['国产龙头', '价格低', '易用性高'], cons: ['大负载不如国外', '生态尚在建设'], bannerImage: '' },
  { id: 'techman-robot', name: 'TM达明', nameCn: '达明协作机器人', category: '工业机器人', description: '达明机器人内建视觉协作臂，不需外部视觉系统，台湾品牌大陆产线', website: 'https://tm-robot.com', specs: { 负载: '4-16kg', 视觉: '内建AI视觉', 精度: '±0.02mm', 编程: '流程图式' }, pricing: '8万元起', features: ['内建AI视觉', '流程图编程', 'AOI检测', '安全协作'], pros: ['内置视觉独特', '编程简单', '检测一体化'], cons: ['台湾品牌', '大负载选择少'], bannerImage: '' },
  { id: 'elite-robot', name: 'Elite艾利特', nameCn: '艾利特协作机器人', category: '工业机器人', description: '艾利特协作机器人，6轴高性价比，焊接/组装/检测多场景应用', website: 'https://elite-robot.com', specs: { 负载: '3-20kg', 臂展: '600-1353mm', 精度: '±0.02mm', 场景: '焊接/组装/检测' }, pricing: '6万元起', features: ['多场景应用', '高性价比', '拖动示教', '生态丰富'], pros: ['价格最低之一', '场景覆盖广', '服务响应快'], cons: ['品牌认知度一般', '精度与头部有差距'], bannerImage: '' },
  { id: 'inovance-automation', name: '汇川机器人', nameCn: '汇川工业机器人', category: '工业机器人', description: '汇川技术工业机器人+伺服系统，国产工控龙头，全产业链自研', website: 'https://inovance.com', specs: { 类型: 'SCARA/六轴', 伺服: '自研伺服系统', 控制器: '自研控制器', 场景: '3C/锂电/光伏' }, pricing: '商用定制', features: ['全自研核心', 'SCARA龙头', '3C/锂电/光伏', '国产替代'], pros: ['国产替代首选', '全产业链', '成本优势'], cons: ['六轴起步晚', '品牌溢价低'], bannerImage: '' },
  { id: 'siasun-robot', name: '新松机器人', nameCn: '新松工业机器人', category: '工业机器人', description: '中科院背景新松机器人，国产工业机器人元老，移动机器人+工业臂', website: 'https://siasun.com', specs: { 类型: '工业臂/移动机器人/AGV', 背景: '中科院', 场景: '汽车/半导体/物流', 资质: '央企' }, pricing: '商用定制', features: ['中科院背景', 'AGV移动机器人', '汽车产线应用', '央企资质'], pros: ['品牌权威', '央企背景', '汽车行业经验'], cons: ['创新速度慢', '价格不低'], bannerImage: '' },
  { id: 'efort-robot', name: '埃夫特机器人', nameCn: '埃夫特工业机器人', category: '工业机器人', description: '埃夫特工业机器人，国产六轴工业臂，汽车/家电/卫浴行业应用', website: 'https://efort.com', specs: { 类型: '六轴工业臂', 负载: '3-210kg', 场景: '汽车/家电/卫浴', 背景:'美的参股' }, pricing: '商用定制', features: ['六轴工业臂', '大负载210kg', '汽车行业应用', '美的生态'], pros: ['大负载国产首选', '美的背书', '汽车行业经验'], cons: ['盈利能力弱', '品牌国际化不足'], bannerImage: '' },

  // ===== 🏥 AI健康穿戴 (5) =====
  { id: 'huawei-watch5', name: '华为Watch 5', nameCn: '华为Watch 5智能手表', category: 'AI健康穿戴', description: '华为旗舰智能手表，玄玑感知系统，血压/心电/血氧/体温全监测', website: 'https://consumer.huawei.com', specs: { 健康: '血压/心电/血氧/体温', 系统: 'HarmonyOS', 续航: '4-14天', 防水: '5ATM+IP68' }, pricing: '2999元起', features: ['血压监测', '心电检测', '玄玑感知', '鸿蒙生态'], pros: ['健康监测最全', '鸿蒙生态', '续航长'], cons: ['血压需校准', 'App功能多但深'], bannerImage: '' },
  { id: 'huawei-band9', name: '华为手环9', nameCn: '华为手环9', category: 'AI健康穿戴', description: '华为高性价比手环，TruSleep4.0睡眠监测，血氧+心率+压力', website: 'https://consumer.huawei.com', specs: { 健康: '心率/血氧/睡眠/压力', 续航: '14天', 重量: '26g', 防水: '5ATM' }, pricing: '249元', features: ['TruSleep4.0', '血氧监测', '压力检测', '14天续航'], pros: ['性价比极高', '睡眠监测准', '轻便'], cons: ['无GPS', '无NFC版贵'], bannerImage: '' },
  { id: 'xiaomi-band9', name: '小米手环9', nameCn: '小米手环9', category: 'AI健康穿戴', description: '小米旗舰手环，AMOLED大屏+150+运动模式，NFC门禁公交', website: 'https://mi.com', specs: { 健康: '心率/血氧/睡眠/压力', 续航: '15天', 屏幕: '1.62寸AMOLED', NFC: '门禁/公交' }, pricing: '249元', features: ['150+运动模式', 'NFC门禁公交', 'AMOLED大屏', '15天续航'], pros: ['性价比最高', '运动模式多', 'NFC实用'], cons: ['睡眠监测不如华为', '偶有断连'], bannerImage: '' },
  { id: 'oppo-watch-x', name: 'OPPO Watch X', nameCn: 'OPPO Watch X智能手表', category: 'AI健康穿戴', description: 'OPPO旗舰手表，双芯双系统，eSIM独立通话+AI健康助手', website: 'https://oppo.com', specs: { 健康: '心率/血氧/睡眠/ECG', 通话: 'eSIM独立', 系统: 'ColorOS Watch', 续航: '2.5-5天' }, pricing: '1999元起', features: ['eSIM独立通话', 'AI健康助手', '双芯长续航', 'ECG心电'], pros: ['独立通话', '安卓体验好', '颜值高'], cons: ['续航一般', '应用生态少'], bannerImage: '' },
  { id: 'dido-watch', name: 'dido智能手表', nameCn: 'dido AI健康手表', category: 'AI健康穿戴', description: 'dido专注健康监测手表，血压/血糖趋势/心电/体温，老年健康首选', website: 'https://dido.com', specs: { 健康: '血压/血糖趋势/心电/体温', 人群: '中老年', 续航: '7天', 通话: '蓝牙通话' }, pricing: '599元起', features: ['血压趋势监测', '血糖趋势', '心电检测', '跌倒报警'], pros: ['健康监测全', '老年友好', '价格低'], cons: ['品牌认知度低', '精度不如医疗设备'], bannerImage: '' },
];
